In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', 50)

In [3]:
df = pd.read_csv('hotel_booking.csv')

In [4]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482

In [5]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'name', 'email',
       'phone-number', 'credit_card'],
      dtype='object')

In [6]:
df = df.drop(columns=[
    'arrival_date_week_number', 'market_segment', 'booking_changes',
    'company', 'days_in_waiting_list', 'total_of_special_requests',
    'email', 'phone-number', 'credit_card'
])

In [7]:
month_string_to_num_map = dict(zip(pd.date_range('2000-01-01', freq='M', periods=12).strftime('%B'), range(1,13)))
month_string_to_num_map

{'January': 1,
 'February': 2,
 'March': 3,
 'April': 4,
 'May': 5,
 'June': 6,
 'July': 7,
 'August': 8,
 'September': 9,
 'October': 10,
 'November': 11,
 'December': 12}

In [8]:
df['arrival_date_month'] = df['arrival_date_month'].map(month_string_to_num_map)

In [9]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,deposit_type,agent,customer_type,adr,required_car_parking_spaces,reservation_status,reservation_status_date,name
0,Resort Hotel,0,342,2015,7,1,0,0,2,0.0,0,BB,PRT,Direct,0,0,0,C,C,No Deposit,NaN,Transient,0.00,0,Check-Out,2015-07-01,Ernest Barnes
1,Resort Hotel,0,737,2015,7,1,0,0,2,0.0,0,BB,PRT,Direct,0,0,0,C,C,No Deposit,NaN,Transient,0.00,0,Check-Out,2015-07-01,Andrea Baker
2,Resort Hotel,0,7,2015,7,1,0,1,1,0.0,0,BB,GBR,Direct,0,0,0,A,C,No Deposit,NaN,Transient,75.00,0,Check-Out,2015-07-02,Rebecca Parker
3,Resort Hotel,0,13,2015,7,1,0,1,1,0.0,0,BB,GBR,Corporate,0,0,0,A,A,No Deposit,304.0,Transient,75.00,0,Check-Out,2015-07-02,Laura Murray
4,Resort Hotel,0,14,2015,7,1,0,2,2,0.0,0,BB,GBR,TA/TO,0,0,0,A,A,No Deposit,240.0,Transient,98.00,0,Check-Out,2015-07-03,Linda Hines
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,8,30,2,5,2,0.0,0,BB,BEL,TA/TO,0,0,0,A,A,No Deposit,394.0,Transient,96.14,0,Check-Out,2017-09-06,Claudia Johnson
119386,City Hotel,0,102,2017,8,31,2,5,3,0.0,0,BB,FRA,TA/TO,0,0,0,E,E,No Deposit,9.0,Transient,225.43,0,Check-Out,2017-09-07,Wesley Aguilar
119387,City Hotel,0,34,2017,8,31,2,5,2,0.0,0,BB,DEU,TA/TO,0,0,0,D,D,No Deposit,9.0,Transient,157.71,0,Check-Out,2017-09-07,Mary Morales
119388,City Hotel,0,109,2017,8,31,2,5,2,0.0,0,BB,GBR,TA/TO,0,0,0,A,A,No Deposit,89.0,Transient,104.40,0,Check-Out,2017-09-07,Caroline Conley MD
119389,City Hotel,0,205,2017,8,29,2,7,2,0.0,0,HB,DEU,TA/TO,0,0,0,A,A,No Deposit,9.0,Transient,151.20,0,Check-Out,2017-09-07,Ariana Michael

In [10]:
df['arrival_date_year'] = pd.to_datetime(
    df[['arrival_date_year', 'arrival_date_month', 'arrival_date_day_of_month']]
        .astype(str)
        .agg('/'.join, axis=1)
)

df.drop(columns=['arrival_date_month', 'arrival_date_day_of_month'], inplace=True)
df.rename(columns={'arrival_date_year': 'arrival_date'}, inplace=True)

In [11]:
df['children'] = df['children'].astype(pd.Int64Dtype())
df['agent'] = df['agent'].astype(pd.Int64Dtype())

In [12]:
df

,hotel,is_canceled,lead_time,arrival_date,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,deposit_type,agent,customer_type,adr,required_car_parking_spaces,reservation_status,reservation_status_date,name
0,Resort Hotel,0,342,2015-07-01,0,0,2,0,0,BB,PRT,Direct,0,0,0,C,C,No Deposit,<NA>,Transient,0.00,0,Check-Out,2015-07-01,Ernest Barnes
1,Resort Hotel,0,737,2015-07-01,0,0,2,0,0,BB,PRT,Direct,0,0,0,C,C,No Deposit,<NA>,Transient,0.00,0,Check-Out,2015-07-01,Andrea Baker
2,Resort Hotel,0,7,2015-07-01,0,1,1,0,0,BB,GBR,Direct,0,0,0,A,C,No Deposit,<NA>,Transient,75.00,0,Check-Out,2015-07-02,Rebecca Parker
3,Resort Hotel,0,13,2015-07-01,0,1,1,0,0,BB,GBR,Corporate,0,0,0,A,A,No Deposit,304,Transient,75.00,0,Check-Out,2015-07-02,Laura Murray
4,Resort Hotel,0,14,2015-07-01,0,2,2,0,0,BB,GBR,TA/TO,0,0,0,A,A,No Deposit,240,Transient,98.00,0,Check-Out,2015-07-03,Linda Hines
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2,5,2,0,0,BB,BEL,TA/TO,0,0,0,A,A,No Deposit,394,Transient,96.14,0,Check-Out,2017-09-06,Claudia Johnson
119386,City Hotel,0,102,2017-08-31,2,5,3,0,0,BB,FRA,TA/TO,0,0,0,E,E,No Deposit,9,Transient,225.43,0,Check-Out,2017-09-07,Wesley Aguilar
119387,City Hotel,0,34,2017-08-31,2,5,2,0,0,BB,DEU,TA/TO,0,0,0,D,D,No Deposit,9,Transient,157.71,0,Check-Out,2017-09-07,Mary Morales
119388,City Hotel,0,109,2017-08-31,2,5,2,0,0,BB,GBR,TA/TO,0,0,0,A,A,No Deposit,89,Transient,104.40,0,Check-Out,2017-09-07,Caroline Conley MD
119389,City Hotel,0,205,2017-08-29,2,7,2,0,0,HB,DEU,TA/TO,0,0,0,A,A,No Deposit,9,Transient,151.20,0,Check-Out,2017-09-07,Ariana Michael

In [13]:
df.to_csv('hotel_booking_cleaned.csv', index=None)